language: csharp
os: linux
dist: trusty
dotnet: 2.1
script:
- dotnet build -c Release
- dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push src/bin/Release/sfdx4csharp.*.nupkg --api-key $NUGET_API_KEY
  on:
    tags: true