version: 1.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore
build:
  project: sfdx4csharp.sln
  verbosity: minimal
  publish_nuget: true
branches:
  only:
    - master
deploy: off  # manual deploy using ui for now
